### DISCUSSION TITLE
What Primers are NOAA Researchers Using?

### DISCUSSION THREAD

**Discussion by marinednadude** [NOAA-Omics/NOAA-Omics#13] [2-Lab]
There are a suite of different metabarcoding and qPCR primer sets that NOAA researchers are using. We're interested in keeping track to serve as a [resource](https://docs.google.com/spreadsheets/d/1c97VY-tOM9IabR7ykgJby5T35C2V6h5lQ9Y_5Ts-a8Y/edit?gid=0#gid=0)

**Comment by lukenoaa** [comment]
Hey @pdenuyl2, I saw your post #14. Check out this one here.

**Comment by lukenoaa** [comment]
This would definitely be useful. I'm wondering, what is the best way to keep track of these primers? Maybe a GitHub repository under @NOAA-Omics that is simply a tab-delimited file of primer sequences? I'm thinking we could use the FAIRe terms as column headers. Here are some example YAML terms from the frontmatter of [AOML's BeBOP protocols](https://github.com/aomlomics/protocols):

### AOML MiFish assay

```yaml
assay_name: ssu12sv5v6_mifish
assay_validation: not provided
targetTaxonomicAssay: 12S rRNA gene sequencing targeting the V5-V6 region using primers MiFish-F V2 and MiFish-R
targetTaxonomicScope: fishes
target_gene: 12S rRNA
target_subfragment: V5-V6
ampliconSize: 163 | 185
pcr_primer_forward: GCCGGTAAAACTCGTGCCAGC
pcr_primer_reverse: CATAGTGGGGTATCTAATCCCAGTTTG
pcr_primer_name_forward: 12S MiFish_U F Fluidigm V2
pcr_primer_name_reverse: 12S MiFish_U R Fluidigm
pcr_primer_reference_forward: http://dx.doi.org/10.1098/rsos.150088
pcr_primer_reference_reverse: http://dx.doi.org/10.1098/rsos.150088
```

### AOML 16S V4-V5 assay

```yaml
assay_name: ssu16sv4v5_emp
assay_validation: not provided
targetTaxonomicAssay: 16S rRNA gene sequencing targeting the V4-V5 region using primers 515F and 926R
targetTaxonomicScope: Prokaryotes, including Bacteria and Archaea
target_gene: 16S rRNA
target_subfragment: V4-V5
ampliconSize: 411
pcr_primer_forward: GTGYCAGCMGCCGCGGTAA
pcr_primer_reverse: CCGYCAATTYMTTTRAGTTT
pcr_primer_name_forward: 515F-Y
pcr_primer_name_reverse: 926R
pcr_primer_reference_forward: 10.1111/1462-2920.13023
pcr_primer_reference_reverse: 10.1111/1462-2920.13023
```

### AOML 18S V9 assay

```yaml
assay_name: ssu18sv9
assay_validation: not provided
targetTaxonomicAssay: 18S rRNA gene sequencing targeting the V9 region using primers 1391F and EukBr
targetTaxonomicScope: Eukaryotes, with a focus on microbial eukaryotic lineages
target_gene: 18S rRNA
target_subfragment: V9
ampliconSize: 260
pcr_primer_forward: GTACACACCGCCCGTC
pcr_primer_reverse: TGATCCTTCTGCAGGTTCACCTAC
pcr_primer_name_forward: 1391F
pcr_primer_name_reverse: EukBr
pcr_primer_reference_forward: 10.1371/journal.pone.0006372
pcr_primer_reference_reverse: 10.1371/journal.pone.0006372
```
